### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it >

### ISSUE THREAD

**Issue by Sarthak-IITKGP** [yilingchung/Towards_KN_CN_Generation#1]
![Solr_error](https://user-images.githubusercontent.com/126904977/222792825-757d5b4c-96ef-4aba-b0a0-8298b99bc6c3.png)
This is the error I am getting when running retrieve_kn_solr.py

**Comment by yilingchung** [comment]
Sorry for not seeing this earlier. Not sure how you arrived to this error on windows, but perhaps you could try these 2:

1. did you index data to the same repository as indicted in call_solr function?
2. change the "localhost" part to "127.0.0.1" (or your real ip) 
see relevant threads [here](https://github.com/Lawouach/WebSocket-for-Python/issues/130) and [here](https://stackoverflow.com/questions/12993276/errno-10061-no-connection-could-be-made-because-the-target-machine-actively-re)

**Comment by Sarthak-IITKGP** [comment]
Thank you for your reply. I solved the problem by running the
retrieve_kn_solr.py code in the windows subsystem for Linux (WSL)
environment and changing the port to respective solr port and hosting solr
on windows powershell.
Sarthak Roy
Research Scholar
Department of CSE
IIT Kharagpur

**Comment by yilingchung** [comment]
Amazing!!
